/*
 * Catering service
 *
 * Notif service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Post /AddNewEmail
// Add new email for notification
func (api *DefaultAPI) AddNewEmailPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /NotifNewDish
// Create new notification in queue
func (api *DefaultAPI) NotifNewDishPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
