// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: notif_new_menu.proto

package notif_new_menu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	mi := &file_notif_new_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_new_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_notif_new_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	mi := &file_notif_new_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notif_new_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_notif_new_menu_proto_rawDescGZIP(), []int{1}
}

func (x *MenuResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_notif_new_menu_proto protoreflect.FileDescriptor

const file_notif_new_menu_proto_rawDesc = "" +
	"\n" +
	"\x14notif_new_menu.proto\x12\x04menu\"'\n" +
	"\vMenuRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fMenuResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2L\n" +
	"\x13NotifNewMenuService\x125\n" +
	"\fNotifNewMenu\x12\x11.menu.MenuRequest\x1a\x12.menu.MenuResponseB\x11Z\x0f/notif_new_menub\x06proto3"

var (
	file_notif_new_menu_proto_rawDescOnce sync.Once
	file_notif_new_menu_proto_rawDescData []byte
)

func file_notif_new_menu_proto_rawDescGZIP() []byte {
	file_notif_new_menu_proto_rawDescOnce.Do(func() {
		file_notif_new_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notif_new_menu_proto_rawDesc), len(file_notif_new_menu_proto_rawDesc)))
	})
	return file_notif_new_menu_proto_rawDescData
}

var file_notif_new_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notif_new_menu_proto_goTypes = []any{
	(*MenuRequest)(nil),  // 0: menu.MenuRequest
	(*MenuResponse)(nil), // 1: menu.MenuResponse
}
var file_notif_new_menu_proto_depIdxs = []int32{
	0, // 0: menu.NotifNewMenuService.NotifNewMenu:input_type -> menu.MenuRequest
	1, // 1: menu.NotifNewMenuService.NotifNewMenu:output_type -> menu.MenuResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notif_new_menu_proto_init() }
func file_notif_new_menu_proto_init() {
	if File_notif_new_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notif_new_menu_proto_rawDesc), len(file_notif_new_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notif_new_menu_proto_goTypes,
		DependencyIndexes: file_notif_new_menu_proto_depIdxs,
		MessageInfos:      file_notif_new_menu_proto_msgTypes,
	}.Build()
	File_notif_new_menu_proto = out.File
	file_notif_new_menu_proto_goTypes = nil
	file_notif_new_menu_proto_depIdxs = nil
}
