// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: notif_new_menu.proto

package notif_new_menu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifNewMenuService_NotifNewMenu_FullMethodName = "/menu.NotifNewMenuService/NotifNewMenu"
)

// NotifNewMenuServiceClient is the client API for NotifNewMenuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifNewMenuServiceClient interface {
	NotifNewMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*MenuResponse, error)
}

type notifNewMenuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifNewMenuServiceClient(cc grpc.ClientConnInterface) NotifNewMenuServiceClient {
	return &notifNewMenuServiceClient{cc}
}

func (c *notifNewMenuServiceClient) NotifNewMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*MenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuResponse)
	err := c.cc.Invoke(ctx, NotifNewMenuService_NotifNewMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifNewMenuServiceServer is the server API for NotifNewMenuService service.
// All implementations must embed UnimplementedNotifNewMenuServiceServer
// for forward compatibility.
type NotifNewMenuServiceServer interface {
	NotifNewMenu(context.Context, *MenuRequest) (*MenuResponse, error)
	mustEmbedUnimplementedNotifNewMenuServiceServer()
}

// UnimplementedNotifNewMenuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifNewMenuServiceServer struct{}

func (UnimplementedNotifNewMenuServiceServer) NotifNewMenu(context.Context, *MenuRequest) (*MenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifNewMenu not implemented")
}
func (UnimplementedNotifNewMenuServiceServer) mustEmbedUnimplementedNotifNewMenuServiceServer() {}
func (UnimplementedNotifNewMenuServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotifNewMenuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifNewMenuServiceServer will
// result in compilation errors.
type UnsafeNotifNewMenuServiceServer interface {
	mustEmbedUnimplementedNotifNewMenuServiceServer()
}

func RegisterNotifNewMenuServiceServer(s grpc.ServiceRegistrar, srv NotifNewMenuServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotifNewMenuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifNewMenuService_ServiceDesc, srv)
}

func _NotifNewMenuService_NotifNewMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifNewMenuServiceServer).NotifNewMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifNewMenuService_NotifNewMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifNewMenuServiceServer).NotifNewMenu(ctx, req.(*MenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifNewMenuService_ServiceDesc is the grpc.ServiceDesc for NotifNewMenuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifNewMenuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "menu.NotifNewMenuService",
	HandlerType: (*NotifNewMenuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifNewMenu",
			Handler:    _NotifNewMenuService_NotifNewMenu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notif_new_menu.proto",
}
