FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main ./cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/dev.env .
COPY --from=builder /app/wait-for-it.sh .
COPY --from=builder /app/wait-all.sh .
COPY --from=builder /app/main .

EXPOSE 8082
EXPOSE 50053

CMD ["./main"]