/*
 * Catering service
 *
 * Notif service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	loggerconfig "github.com/KusakinDev/Catering-Notif-Service/internal/config/logger"
	routerpkg "github.com/KusakinDev/Catering-Notif-Service/internal/routes"
	rabbitmq "github.com/KusakinDev/Catering-Notif-Service/internal/utils/RabbitMQ"
)

func main() {
	loggerconfig.Init()

	var rmq rabbitmq.RabbitMQ
	rmq.InitConnection()
	rmq.InitChannel()
	rmq.InitConsumer("emailQueue")
	go rmq.ConsumeNotif()

	routes := routerpkg.ApiHandleFunctions{}
	routes.DefaultAPI.RMQ = &rmq

	log.Printf("Server started")

	router := routerpkg.NewRouter(routes)

	log.Fatal(router.Run(":8082"))
}
