/*
 * Catering service
 *
 * Notif service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	routerpkg "github.com/KusakinDev/Catering-Notif-Service/internal/routes"
)

func main() {
	routes := routerpkg.ApiHandleFunctions{}

	log.Printf("Server started")

	router := routerpkg.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
