/*
 * Catering service
 *
 * Notif service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NotifNewDishRequest struct {

	Name string `json:"name,omitempty"`
}
