/*
 * Catering service
 *
 * Notif service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AddNewEmailRequest struct {

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	Email string `json:"email,omitempty"`
}
